### ISSUE TITLE
Feature Request: Netlify Image CDN using Astro Adapter?

### ISSUE THREAD

**Issue by theapplegates** [stevefrenzel/astro-naut#2]
https://www.netlify.com/blog/astro-netlify-adapter/

Is this something that would be easy to implement?
I tried to do it but could not get it to work.
But for those who code it might be easy. Any thoughts?
Paul

**Comment by stevefrenzel** [comment]
Hey @theapplegates, thanks for your request!

I looked into it and implementation is straightforward: [Documentation](https://docs.astro.build/en/guides/integrations-guide/netlify/) However, I don't see a benefit as I'm using Vercel for deployment, where this is not necessary.

But you are welcome to add this to you project if you're using it. It is a highly opinionated starter template but I encourage anyone to adjust it to their liking. 🤗

**Comment by theapplegates** [comment]
You're right. I see how they are similar. I appreciate the feedback.
Paul
