### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by jeanlucaslima** [stevefrenzel/astro-naut#3]
This is just a thank you for such a wonderful work. This repo is exemplar and I will be using it as reference for my next Astro project. 

I like the Fluid design provocations, but I'm not sure how to do fluid design menus when you have several pages, would love to see some insights for that. 

Then again, thanks for this, it's an awesome project.

**Comment by stevefrenzel** [comment]
> This is just a thank you for such a wonderful work. This repo is exemplar and I will be using it as reference for my next Astro project.
> 
> I like the Fluid design provocations, but I'm not sure how to do fluid design menus when you have several pages, would love to see some insights for that.
> 
> Then again, thanks for this, it's an awesome project.

Thank you so much @jeanlucaslima, you just made my day! ❤️

Can you be more specific regarding "fluid design menus"? When done right, it using this approaching should cause less problems and not more but I'm happy to discuss this topic.

You can reach out to me via [email](stvfrnzl@duck.go) at or on [Mastodon](https://mastodon.online/@stvfrnzl).

Happy new year! 🍾
